In [ ]:
#SET UP FOR NOTEBOOK. RUN THIS CELL FIRST
import numpy as np


def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    
    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]
    
    #recursively call block on each quadrant
    #store value in submatrix list.
    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

In [2]:
import numpy as np
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
#shape returns a tuple w the dimensions of the array
print(A.shape)

B = np.array([1,2,3])
print(B.shape)

C = np.array([1])
print(C.shape)

(3, 3)
(3,)
(1,)


In [3]:
D = np.array([[1,2],
            [3,4]])
            
def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

    
    
print(block(D))
    

[array([[1, 2],
       [3, 4]])]


In [4]:
def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]
    
    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2


print(block(D))   

[array([[1, 2],
       [3, 4]])]


In [5]:

C  = np.arange(1, 65).reshape(8, 8)

def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    print(mid_col)


print(block(C))

4
None


```:mid_row``` specifies a range from the beginning of the matrix up to (but not including)
the mid_row index. This extracts the rows from index 0 to mid_row - 1

 By combining these two slicing operations, ```matrix[:mid_row, :mid_col]``` extracts the submatrix consisting of the rows from index 0 to mid_row - 1 and the columns from index 0 to mid_col - 1. This submatrix represents the top-left quadrant of the original matrix.

In [6]:

C  = np.arange(1, 65).reshape(8, 8)

def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    
    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]
    print(quadrant1)
    print(quadrant2)
    print(quadrant3)
    print(quadrant4)

print(block(C))

[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]
 [25 26 27 28]]
[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]
 [29 30 31 32]]
[[33 34 35 36]
 [41 42 43 44]
 [49 50 51 52]
 [57 58 59 60]]
[[37 38 39 40]
 [45 46 47 48]
 [53 54 55 56]
 [61 62 63 64]]
None


In [3]:
import numpy as np
C  = np.arange(1, 65).reshape(8, 8)

def block(matrix):
    rows, cols = matrix.shape
     # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    
    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]
    print(quadrant1)
    print(quadrant2)
    print(quadrant3)
    print(quadrant4)

    submatrix = []

    submatrix.extend(block(quadrant1))

    return submatrix


In [4]:
import numpy as np 
#generate test array
X  = np.arange(1, 65).reshape(8, 8)
           
def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    
    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]
    
    #recursively call block on each quadrant
    #store value in submatrix list.
    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix


print(block(X))


[array([[ 1,  2],
       [ 9, 10]]), array([[ 3,  4],
       [11, 12]]), array([[17, 18],
       [25, 26]]), array([[19, 20],
       [27, 28]]), array([[ 5,  6],
       [13, 14]]), array([[ 7,  8],
       [15, 16]]), array([[21, 22],
       [29, 30]]), array([[23, 24],
       [31, 32]]), array([[33, 34],
       [41, 42]]), array([[35, 36],
       [43, 44]]), array([[49, 50],
       [57, 58]]), array([[51, 52],
       [59, 60]]), array([[37, 38],
       [45, 46]]), array([[39, 40],
       [47, 48]]), array([[53, 54],
       [61, 62]]), array([[55, 56],
       [63, 64]])]


In [11]:
A  = np.arange(1, 17).reshape(4, 4)
print(block(A))

q1, q2, q3, q4 = block(A)
print(q1)
print(q2)
print(q1 + q2)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]]), array([[ 9, 10],
       [13, 14]]), array([[11, 12],
       [15, 16]])]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[ 4  6]
 [12 14]]


In [9]:
import numpy as np

def block_n(matrix):
    dimensions = matrix.shape
    return dimensions
print(block_n(A))

(4, 4)


but what if i have n dimension???


In [2]:
#n dimension test case
n = (4, 4, 4)

def test_case(dimensions):
    val = np.arange(1, np.prod(n) + 1)
    matrix = np.reshape(val, dimensions)
    return matrix

testme = test_case(n)
print(testme)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


In [1]:
import numpy as np

def block(matrix):
    dimensions = matrix.shape
    ndims = len(dimensions)
    
    # Base case: return itself
    if all(dim <= 2 for dim in dimensions):
        return [matrix]

    # Split the matrix along each dimension
    submatrices = []
    for i in range(ndims):
        mid = dimensions[i] // 2
        slices = [slice(None)] * ndims  # create a list of slices for indexing
        slices[i] = slice(None, mid)  # slice for the first half along current dimension
        submatrix1 = matrix[tuple(slices)]
        slices[i] = slice(mid, None)  # slice for the second half along current dimension
        submatrix2 = matrix[tuple(slices)]
        submatrices.extend(block(submatrix1))  # recursively call block on each submatrix
        submatrices.extend(block(submatrix2))

    return submatrices



In [14]:
arr4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print('thsi is without block')
print(arr4d)

this = block(arr4d)
print('this is w block')
print(this)
print(testme)



thsi is without block
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
this is w block
[array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


RecursionError: maximum recursion depth exceeded in comparison