In [6]:
import numpy as np
A = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
#shape returns a tuple w the dimensions of the array
print(A.shape)

B = np.array([1,2,3])
print(B.shape)

C = np.array([1])
print(C.shape)

(3, 3)
(3,)
(1,)


In [7]:
D = np.array([[1,2],
            [3,4]])
            
def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

    
    
print(block(D))
    

[array([[1, 2],
       [3, 4]])]


In [8]:
def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]
    
    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2


print(block(D))   

[array([[1, 2],
       [3, 4]])]


In [9]:
 #same thing as B but better.
C  = np.arange(1, 65).reshape(8, 8)

def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    print(mid_col)


print(block(C))

4
None


```:mid_row``` specifies a range from the beginning of the matrix up to (but not including)
the mid_row index. This extracts the rows from index 0 to mid_row - 1

 By combining these two slicing operations, ```matrix[:mid_row, :mid_col]``` extracts the submatrix consisting of the rows from index 0 to mid_row - 1 and the columns from index 0 to mid_col - 1. This submatrix represents the top-left quadrant of the original matrix.

In [10]:
 #same thing as B but better.
C  = np.arange(1, 65).reshape(8, 8)

def block(matrix):
    rows, cols = matrix.shape
    #base case, return itself
    if rows <= 2 and cols <= 2:
        return [matrix]

     # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2
    
    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]
    print(quadrant1)

print(block(C))

[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]
 [25 26 27 28]]
None
