In [22]:
import numpy as np


A = np.arange(1, 10).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)
C = np.arange(1, 17).reshape(4, 4)
#OR
#matrix_size = 3  
#A = np.random.rand(matrix_size, matrix_size)

print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    row1 = len(A)
    row2 = len(B)
    col1 = len(A[0])
    col2 = len(B[0])
    if row2 != col1:
        print("dimension error")
    
    print(col1)
    print(row2)
ijk_mm(A,C)

dimension error
3
4


In [30]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    print(result)
ijk_mm(A,B)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
