In [1]:
import numpy as np


#A = np.arange(1, 10).reshape(3, 3)
#B = np.arange(1, 10).reshape(3, 3)
#C = np.arange(1, 17).reshape(4, 4)
#OR
matrix_size = 4  
A = np.random.rand(matrix_size, matrix_size)
B = np.random.rand(matrix_size, matrix_size)


print(A)
print(B)

[[0.85853421 0.94588282 0.45231243 0.31577077]
 [0.6422389  0.26946686 0.64022538 0.68253777]
 [0.97170141 0.81659173 0.24298888 0.38624154]
 [0.34594874 0.2830319  0.18755824 0.89362044]]
[[0.00198682 0.0694842  0.61485182 0.01419092]
 [0.86492845 0.16364515 0.88381685 0.34050181]
 [0.19379603 0.24415522 0.45779275 0.72503998]
 [0.65470856 0.60159388 0.63956677 0.31198234]]


In [2]:
#using a decorator to calculate execution time
import time
import math

def timeit(func):
    #if function takes arguments, can be added like this
    def inner1(*args, **kwargs):
        begin = time.time()
        
        func(*args, **kwargs)
        
        end = time.time()
        
        print("time to execute : ", func.__name__, end - begin)
        
    return inner1

In [3]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    row1 = len(A)
    row2 = len(B)
    col1 = len(A[0])
    col2 = len(B[0])
    if row2 != col1:
        print("dimension error")
    
    print(col1)
    print(row2)
ijk_mm(A,C)

NameError: name 'C' is not defined

In [4]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    print(result)
ijk_mm(A,B)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [5]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    for row in result:
        print(row)
        
ijk_mm(A,B)

[1.1142209036686936, 0.5148439052157869, 1.7728803386296836, 0.7607177030688035]
[0.8052820269078167, 0.655647313794715, 1.3626601197410364, 0.7779966436477297]
[1.0081899400405137, 0.4928367233367284, 1.6774357089313117, 0.5885174893760273]
[0.8668986753915731, 0.6537446784337162, 1.1202483131642276, 0.5160632222383249]


# timing w homebrew timer

In [6]:
@timeit
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    for row in result:
        print(row)
        
ijk_mm(A,B)

[1.1142209036686936, 0.5148439052157869, 1.7728803386296836, 0.7607177030688035]
[0.8052820269078167, 0.655647313794715, 1.3626601197410364, 0.7779966436477297]
[1.0081899400405137, 0.4928367233367284, 1.6774357089313117, 0.5885174893760273]
[0.8668986753915731, 0.6537446784337162, 1.1202483131642276, 0.5160632222383249]
time to execute :  ijk_mm 0.0001251697540283203


In [7]:
import timeit
execute_time = []
setup = '''
matrix_size = 256
from __main__ import ijk_mm
import numpy as np

A = np.random.rand(matrix_size,matrix_size)
B = np.random.rand(matrix_size,matrix_size)
'''
statement = 'ijk_mm(A, B)'

execute_time.append(timeit.timeit(statement, setup=setup, number=1))

[61.140527111316935, 62.09140312983484, 63.5586695216939, 65.08768629345212, 60.29850046463688, 58.91164270265371, 61.46463756781564, 64.56294209697819, 61.90563688186427, 59.852911157094226, 61.61176333865968, 67.99017654868855, 62.68766515831567, 57.035354337945485, 61.45176616413928, 61.22306088253962, 62.246047310594975, 61.346024329126806, 57.06008096774295, 57.5372582530969, 58.7048198240819, 62.92384655816367, 57.87503186032963, 61.961324170457644, 60.44230467153593, 63.7853185836198, 65.1483582799637, 58.88709191776592, 60.56319129888135, 63.604554599504155, 59.91586598267406, 59.58266128897399, 63.63284946548865, 59.68509060309237, 59.36950646722051, 64.29501092617986, 60.89332694216311, 58.476974963083116, 65.11828698907793, 61.868712683593216, 62.29697552357252, 66.70523935661555, 60.28203474214637, 62.11632123389452, 64.94630022198969, 60.64246599722727, 63.29936875881632, 65.02177896622499, 59.54318838257909, 64.4920415885926, 59.236789471790715, 65.61999924672183, 61.2581

In [4]:

import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result



Z = np.arange(1, 17).reshape(4, 4)
Y = np.arange(1, 17).reshape(4, 4)
q1, q2, q3, q4 = block(ijk_mm(Z,Y))

print(q1,q2,q3,q4)
ijk_mm(q1, q2) + ijk_mm(q3, q4)



[[ 90. 100.]
 [202. 228.]] [[110. 120.]
 [254. 280.]] [[314. 356.]
 [426. 484.]] [[398. 440.]
 [542. 600.]]


array([[353224., 390560.],
       [512008., 565920.]])

In [4]:

import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result



Z = np.arange(1, 17).reshape(4, 4)
Y = np.arange(1, 17).reshape(4, 4)
q1, q2, q3, q4 = block(ijk_mm(Z,Y))

print(q1,q2,q3,q4)
ijk_mm(q1, q2) + ijk_mm(q3, q4)



[[ 90. 100.]
 [202. 228.]] [[110. 120.]
 [254. 280.]] [[314. 356.]
 [426. 484.]] [[398. 440.]
 [542. 600.]]


array([[353224., 390560.],
       [512008., 565920.]])

In [20]:

import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result


#TESTING...
A = np.arange(1, 17).reshape(4, 4)
B = np.arange(1, 17).reshape(4, 4)

A_quadrant1, A_quadrant2, A_quadrant3, A_quadrant4 = block(A)
B_quadrant1, B_quadrant2, B_quadrant3, B_quadrant4 = block(B)

Result_00 = ijk_mm(A_quadrant1, B_quadrant1) + ijk_mm(A_quadrant1, B_quadrant2)
print(Result_00)

#...


[[ 28.  34.]
 [ 92. 114.]]
