In [22]:
import numpy as np


A = np.arange(1, 10).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)
C = np.arange(1, 17).reshape(4, 4)
#OR
#matrix_size = 3  
#A = np.random.rand(matrix_size, matrix_size)

print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    row1 = len(A)
    row2 = len(B)
    col1 = len(A[0])
    col2 = len(B[0])
    if row2 != col1:
        print("dimension error")
    
    print(col1)
    print(row2)
ijk_mm(A,C)

dimension error
3
4


In [30]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    print(result)
ijk_mm(A,B)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [ ]:
import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result



Z = np.arange(1, 17).reshape(4, 4)
Y = np.arange(1, 17).reshape(4, 4)
q1, q2, q3, q4 = block(ijk_mm(Z,Y))

print(q1)




: 