In [6]:
import numpy as np


#A = np.arange(1, 10).reshape(3, 3)
#B = np.arange(1, 10).reshape(3, 3)
C = np.arange(1, 17).reshape(4, 4)
#OR
matrix_size = 4  
A = np.random.rand(matrix_size, matrix_size)
B = np.random.rand(matrix_size, matrix_size)


print(A)
print(B)

[[0.39969152 0.08721791 0.03591984 0.30555933]
 [0.99563315 0.52312975 0.18247281 0.7342443 ]
 [0.07547338 0.5282823  0.43260333 0.94102031]
 [0.06308547 0.59737118 0.13160059 0.96832797]]
[[0.08753088 0.44628771 0.06388255 0.12350883]
 [0.83816404 0.66513041 0.17535156 0.32114878]
 [0.14280724 0.53797191 0.22976456 0.97072313]
 [0.06908333 0.42056469 0.81145394 0.79552822]]


In [7]:
#using a decorator to calculate execution time
import time
import math

def timeit(func):
    #if function takes arguments, can be added like this
    def inner1(*args, **kwargs):
        begin = time.time()
        
        func(*args, **kwargs)
        
        end = time.time()
        
        print("time to execute : ", func.__name__, end - begin)
        
    return inner1

In [8]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    row1 = len(A)
    row2 = len(B)
    col1 = len(A[0])
    col2 = len(B[0])
    if row2 != col1:
        print("dimension error")
    
    print(col1)
    print(row2)
ijk_mm(A,C)

4
4


In [9]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    print(result)
ijk_mm(A,B)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [10]:
#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    for row in result:
        print(row)
        
ijk_mm(A,B)

[0.13432693299176393, 0.3842200266184153, 0.29702753830637096, 0.35532464573867106]
[0.6023996676905483, 1.199250821716239, 0.793066415443849, 1.0522146058362574]
[0.5761811856915369, 1.013547820585842, 0.9604481044846049, 1.3475251065873715]
[0.5919058066397176, 0.9035259805806933, 0.9247707216099075, 1.0977165894755574]


# timing w homebrew timer

In [11]:
@timeit
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = [[0 for _ in range(colsB)] for _ in range(rowsA)]
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    for row in result:
        print(row)
        
ijk_mm(A,B)

[0.13432693299176393, 0.3842200266184153, 0.29702753830637096, 0.35532464573867106]
[0.6023996676905483, 1.199250821716239, 0.793066415443849, 1.0522146058362574]
[0.5761811856915369, 1.013547820585842, 0.9604481044846049, 1.3475251065873715]
[0.5919058066397176, 0.9035259805806933, 0.9247707216099075, 1.0977165894755574]
time to execute :  ijk_mm 0.0006809234619140625


In [2]:
import timeit
execute_time = []
setup = '''
matrix_size = 16
from __main__ import ijk_mm
import numpy as np

A = np.random.rand(matrix_size,matrix_size)
B = np.random.rand(matrix_size,matrix_size)
'''
statement = 'ijk_mm(A, B)'

execute_time.append(timeit.timeit(statement, setup=setup, number=1))

[3.2789863344431067, 3.197719172308503, 4.501940041220473, 4.103682317112822, 2.540923063441926, 3.1699204321386567, 3.033124865298663, 3.8514272699100607, 3.4926088856617534, 4.048407177552331, 2.531667868514116, 3.4172382821055454, 3.885632278032662, 2.9058803459872204, 4.288563313999594, 3.6562955652958786]
[4.388556114533984, 4.126608600831791, 6.324501210396096, 5.259557272300188, 2.8818016106063395, 4.484362113681337, 2.9730408751051782, 4.381104364659285, 3.464194418352691, 5.775704079955238, 3.4439568025671226, 4.077325383469373, 5.752251744914599, 4.4898000510117395, 4.501944044636601, 5.16211702769922]
[4.137360754396588, 3.0413563485993853, 4.626800912451181, 4.248554956143921, 2.549061459504757, 3.5992858883997574, 3.1116295215824716, 3.4354994709205338, 3.6335811854272064, 4.284446353107088, 2.8418173893837197, 3.994928844278367, 4.591000700170287, 3.306962274364077, 3.9106570801998184, 3.5508622180718277]
[4.429897660590278, 4.029406823185486, 6.194212126151899, 5.5099102

In [ ]:

import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result



Z = np.arange(1, 17).reshape(4, 4)
Y = np.arange(1, 17).reshape(4, 4)
q1, q2, q3, q4 = block(ijk_mm(Z,Y))

print(q1,q2,q3,q4)
ijk_mm(q1, q2) + ijk_mm(q3, q4)



[[ 90. 100.]
 [202. 228.]] [[110. 120.]
 [254. 280.]] [[314. 356.]
 [426. 484.]] [[398. 440.]
 [542. 600.]]


array([[353224., 390560.],
       [512008., 565920.]])

In [ ]:

import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result



Z = np.arange(1, 17).reshape(4, 4)
Y = np.arange(1, 17).reshape(4, 4)
q1, q2, q3, q4 = block(ijk_mm(Z,Y))

print(q1,q2,q3,q4)
ijk_mm(q1, q2) + ijk_mm(q3, q4)



[[ 90. 100.]
 [202. 228.]] [[110. 120.]
 [254. 280.]] [[314. 356.]
 [426. 484.]] [[398. 440.]
 [542. 600.]]


array([[353224., 390560.],
       [512008., 565920.]])

In [34]:

import numpy as np
def block(matrix):
    rows, cols = matrix.shape

    # Base case, return itself
    if rows <= 2 and cols <= 2:
        return np.array([matrix])

    # Split the matrix into four quadrants
    mid_row = rows // 2
    mid_col = cols // 2

    quadrant1 = matrix[:mid_row, :mid_col]
    quadrant2 = matrix[:mid_row, mid_col:]
    quadrant3 = matrix[mid_row:, :mid_col]
    quadrant4 = matrix[mid_row:, mid_col:]

    submatrix = []
    submatrix.extend(block(quadrant1))
    submatrix.extend(block(quadrant2))
    submatrix.extend(block(quadrant3))
    submatrix.extend(block(quadrant4))
   

    return submatrix

#ijk loop
def ijk_mm(A,B):
    #check dimensions for compatibility
    rowsA = len(A)
    rowsB = len(B)
    colsA = len(A[0])
    colsB = len(B[0])
    if rowsB != colsA:
        print("dimension error")

    result = np.zeros((rowsA, colsB))
    
    for i in range(rowsA):
        for j in range(colsB):
            for k in range(colsA):
                result[i][j] += A[i][k] * B[k][j]
    return result


#TESTING...
A = np.arange(1, 17).reshape(4, 4)
B = np.arange(1, 17).reshape(4, 4)

A_NW, A_NE, A_SW, A_SE = block(A)
B_NW, B_NE, B_SW, B_SE = block(B)
testme = ijk_mm(A, B)
print(testme)

def ijk_block(A, B):
    A_NW, A_NE, A_SW, A_SE = block(A)
    B_NW, B_NE, B_SW, B_SE = block(B)
    Result_00 = ijk_mm(A_NW, B_NW) + ijk_mm(A_NE, B_SW)
    Result_01 = ijk_mm(A_NW, B_NE) + ijk_mm(A_NE, B_SE)
    Result_10 = ijk_mm(A_SW, B_NW) + ijk_mm(A_SE, B_SW)
    Result_11 = ijk_mm(A_SW, B_NE) + ijk_mm(A_SE, B_SE)
    Result = np.block([[Result_00, Result_01], [Result_10, Result_11]])
    return Result
    

def ans(A_NW, A_NE, A_SW, A_SE, B_NW, B_NE, B_SW, B_SE):

    Result_00 = ijk_mm(A_NW, B_NW) + ijk_mm(A_NE, B_SW)
    Result_01 = ijk_mm(A_NW, B_NE) + ijk_mm(A_NE, B_SE)
    Result_10 = ijk_mm(A_SW, B_NW) + ijk_mm(A_SE, B_SW)
    Result_11 = ijk_mm(A_SW, B_NE) + ijk_mm(A_SE, B_SE)
    Result = np.block([[Result_00, Result_01], [Result_10, Result_11]])
    return Result

testme1= ijk_block(A, B) 
print(A)
print(testme1)




[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]
