my notes from [TensorFlow](https://www.tensorflow.org/tutorials/quickstart/beginner)

- check TensorFlow version with the following command 

In [22]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


    now import the MNIST dataset. The pixel values of the images range from 0 through 255. Scale these values to a range of 0 to 1 by dividing the values by 255.0. This also converts the sample data from integers to floating-point numbers:

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


# Build a machine learning model

Build a ```tf.keras.Sequential```s model:


In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

[`Sequential`](https://www.tensorflow.org/guide/keras/sequential_model) is useful for stacking layers where each layer has one input [tensor](https://www.tensorflow.org/guide/tensor) and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the [`Flatten`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Flatten), [`Dense`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense), and [`Dropout`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout) layers.

For each example, the model returns a vector of [logits](https://developers.google.com/machine-learning/glossary#logits) or [log-odds](https://developers.google.com/machine-learning/glossary#log-odds) scores, one for each class.

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.70252055,  0.41559777, -0.5264201 ,  0.36003548, -0.14209002,
        -1.2794709 , -0.33003104, -0.5786648 , -0.09857407,  0.6588159 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.18654718, 0.14001665, 0.05458415, 0.1324492 , 0.08016392,
        0.02570518, 0.06642893, 0.05180563, 0.08372934, 0.1785698 ]],
      dtype=float32)

- define a loss function

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [16]:
loss_fn(y_train[:1], predictions).numpy()

3.6610627

Before you start training, configure and compile the model using Keras `Model.compile`. Set the [`optimizer`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers) class to `adam`, set the `loss` to the `loss_fn` function you defined earlier, and specify a metric to be evaluated for the model by setting the `metrics` parameter to `accuracy`.

In [17]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## Train and evaluate your model

Use the `Model.fit` method to adjust your model parameters and minimize the loss: 

In [18]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 1ms/step - loss: 0.2977 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1444 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1080 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0872 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0745 - accuracy: 0.9765


The Model.evaluate method checks the model's performance, usually on a validation set or test set.


In [19]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0708 - accuracy: 0.9774 - 377ms/epoch - 1ms/step


[0.07077331095933914, 0.977400004863739]

In [21]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0260934e-07, 2.4180751e-09, 1.4324409e-05, 5.8679521e-04,
        2.0665678e-11, 3.5590483e-07, 3.3014951e-12, 9.9939346e-01,
        2.7834703e-06, 2.2393408e-06],
       [2.3044889e-07, 4.2401545e-04, 9.9949729e-01, 3.0085139e-05,
        2.2316727e-13, 4.8112837e-05, 9.2978787e-08, 6.8019715e-11,
        1.4055925e-07, 4.6444015e-11],
       [7.2609719e-06, 9.9740320e-01, 5.0753320e-04, 1.9782785e-05,
        1.9134778e-04, 6.6168519e-05, 1.9671008e-04, 1.0173905e-03,
        5.6776818e-04, 2.2851162e-05],
       [9.9994206e-01, 6.6718564e-09, 4.4313627e-05, 8.9707292e-08,
        4.3692076e-08, 2.0092541e-06, 3.9502711e-06, 6.6227117e-06,
        5.2709943e-08, 9.4767171e-07],
       [1.0087297e-05, 3.8873580e-09, 1.7220551e-06, 3.0294721e-08,
        9.9508697e-01, 8.6674199e-06, 2.9824903e-06, 1.1879695e-04,
        4.9679539e-07, 4.7701690e-03]], dtype=float32)>